import React from "react";

export const styles: Record<string, React.CSSProperties> = {
  container: {
    display: "flex",
    flexDirection: "column",
    height: "100vh",
    maxWidth: 800,
    margin: "0 auto",
    backgroundColor: "#0f172a",
    color: "#e2e8f0",
    fontFamily: "system-ui, -apple-system, sans-serif",
  },
  header: {
    padding: "16px 20px",
    borderBottom: "1px solid #1e293b",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 8,
  },
  title: { fontSize: 18, fontWeight: 700, margin: 0 },
  config: { display: "flex", alignItems: "center", gap: 12, fontSize: 13 },
  configLabel: { display: "flex", alignItems: "center", gap: 4, cursor: "pointer" },
  endpointInput: {
    padding: "4px 8px",
    fontSize: 13,
    borderRadius: 4,
    border: "1px solid #334155",
    backgroundColor: "#1e293b",
    color: "#e2e8f0",
    width: 200,
  },
  chatArea: {
    flex: 1,
    overflowY: "auto",
    padding: "16px 20px",
    display: "flex",
    flexDirection: "column",
    gap: 12,
  },
  emptyHint: {
    color: "#475569",
    textAlign: "center",
    marginTop: 80,
    fontSize: 14,
  },
  bubbleRow: { display: "flex" },
  bubble: {
    maxWidth: "80%",
    padding: "10px 14px",
    borderRadius: 12,
    fontSize: 14,
  },
  bubbleRole: { fontSize: 11, color: "#94a3b8", marginBottom: 4 },
  cursor: {
    display: "inline-block",
    backgroundColor: "#3b82f6",
    width: 2,
    height: 16,
    verticalAlign: "text-bottom",
    animation: "blink 0.8s infinite",
    marginLeft: 1,
  },
  streamBar: {
    padding: "8px 20px",
    fontSize: 12,
    borderTop: "1px solid #1e293b",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
  },
  abortBtn: {
    background: "none",
    border: "1px solid #475569",
    color: "#94a3b8",
    padding: "2px 8px",
    borderRadius: 4,
    fontSize: 11,
    cursor: "pointer",
  },
  correctGroup: {
    display: "flex",
    gap: 4,
    alignItems: "center",
  },
  correctBtn: {
    background: "none",
    border: "1px solid #3b82f6",
    color: "#93c5fd",
    padding: "2px 8px",
    borderRadius: 4,
    fontSize: 11,
    cursor: "pointer",
  },
  inputArea: {
    padding: "12px 20px",
    borderTop: "1px solid #1e293b",
    display: "flex",
    gap: 8,
  },
  textInput: {
    flex: 1,
    padding: "10px 14px",
    fontSize: 14,
    borderRadius: 8,
    border: "1px solid #334155",
    backgroundColor: "#1e293b",
    color: "#e2e8f0",
    outline: "none",
  },
  sendBtn: {
    padding: "10px 20px",
    fontSize: 14,
    fontWeight: 600,
    borderRadius: 8,
    border: "none",
    backgroundColor: "#3b82f6",
    color: "#fff",
    cursor: "pointer",
  },
  // ---- JSON 卡片样式 ----
  card: {
    margin: "8px 0",
    borderRadius: 8,
    border: "1px solid #334155",
    backgroundColor: "#1a2332",
    overflow: "hidden",
  },
  cardHeader: {
    padding: "6px 12px",
    fontSize: 12,
    fontWeight: 600,
    color: "#94a3b8",
    backgroundColor: "#0f172a",
    borderBottom: "1px solid #1e293b",
    textTransform: "uppercase" as const,
    letterSpacing: "0.5px",
  },
  cardBody: {
    padding: "10px 12px",
    fontSize: 13,
  },
  cardJson: {
    margin: 0,
    fontSize: 11,
    fontFamily: "monospace",
    color: "#94a3b8",
    whiteSpace: "pre-wrap" as const,
    wordBreak: "break-all" as const,
  },
  weatherRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "3px 0",
    fontSize: 13,
    borderBottom: "1px solid #1e293b55",
  },
  routeDay: {
    marginBottom: 8,
    padding: "6px 8px",
    borderRadius: 6,
    backgroundColor: "#0f172a55",
  },
  routeDayLabel: {
    fontSize: 12,
    fontWeight: 600,
    color: "#fbbf24",
    marginBottom: 4,
  },
  errorCard: {
    display: "inline-block",
    margin: "4px 0",
    padding: "6px 12px",
    borderRadius: 6,
    backgroundColor: "#451a1a",
    border: "1px solid #7f1d1d",
    color: "#fca5a5",
    fontSize: 12,
  },
};
